import { Link } from 'react-router-dom';
import { ArrowRight } from 'lucide-react';
import useSeo from '../lib/seo.js';
import { Eyebrow } from '../components/ui.jsx';
import { audiences } from '../data/audiences.js';
import asset from '../lib/asset.js';

export default function Proof() {
  useSeo({title:'Mr Property Siam | HostPilot Pro client showcase',description:'HostPilot Pro is the software. Mr Property Siam is the founding operator and client using it across operations, owners and guests.',path:'/proof'});
  return <div className="pt-16">
    <section className="shell-wide py-12 sm:py-16"><Eyebrow>Client showcase · Koh Samui, Thailand</Eyebrow><h1 className="h-sec mt-4 max-w-4xl">Mr Property Siam.<br /><span className="serif-em text-hp-text2">The operation behind the software.</span></h1><p className="mt-6 text-[18px] text-hp-text2 leading-relaxed max-w-3xl">HostPilot Pro is the management software. Mr Property Siam is the property management company that built it for its own operation and uses it with its office, owners and guests.</p><p className="mt-4 text-[15px] text-hp-text3">This is our founding client example, not an independent customer testimonial.</p></section>
    <section className="band py-12 sm:py-16"><div className="shell-wide grid gap-10 md:grid-cols-2 md:items-center"><img src={asset('/img/samui-coast.jpg')} alt="Koh Samui coastline" className="rounded-2xl w-full border border-hp-line" /><div><Eyebrow>Built around the work</Eyebrow><h2 className="h-sec mt-3">Three perspectives.<br /><span className="serif-em text-hp-text2">One management business.</span></h2><p className="mt-5 text-[16px] leading-relaxed text-hp-text2">The office needs to coordinate the operation. Owners need to understand their property and money. Guests need a straightforward stay experience. HostPilot Pro gives each group its own view.</p><p className="mt-4 text-[15px] leading-relaxed text-hp-text3">The MPS owner-portal walkthrough supplies the real deployment example used in the owner section. Other selected screens are clearly labelled demo replicas, not MPS client records.</p></div></div></section>
    <section className="shell-wide py-12 sm:py-16"><div className="grid gap-5 md:grid-cols-3">{audiences.map((a)=><article className="hp-card p-6" key={a.key}><Eyebrow>{a.label}</Eyebrow><h2 className="font-display text-[26px] mt-4">{a.product}</h2><p className="mt-4 text-[15px] leading-relaxed text-hp-text2">{a.body}</p><Link to={a.to} className="mt-5 inline-flex items-center gap-2 text-[14px] text-hp-goldInk">See the core functions <ArrowRight size={15} /></Link></article>)}</div><div className="client-strip mt-10"><div><Eyebrow>A practical next step</Eyebrow><h2 className="font-display text-[28px] mt-3">Ask to see your workflows.</h2></div><p>No invented savings percentage, customer quote or return-on-investment claim. Bring the workflows that matter to you and review the fit in a guided demonstration.</p><Link to="/demo" className="btn btn-gold">Book a call <ArrowRight size={15} /></Link></div></section>
  </div>;
}
