import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Megaphone, Image, Mail, CheckCircle2, ShieldCheck, CalendarDays } from 'lucide-react';
import asset from '../lib/asset.js';
import './marketing-visual-story.css';
const modes = [
  { key:'campaigns', icon:Megaphone, name:'Campaign planning', title:'Turn an open stay window into a campaign brief.', text:'Use available nights as the starting point. Prepare Google and Meta campaign drafts, review the creative and budget, then approve actions through configured provider connections.', status:'Paused draft · review required', previewTitle:'Villa Azure · a seven-night opening', previewBody:'A fictional campaign brief, built around an available stay window.', fields:[['Channels','Google & Meta'],['Proposed budget','฿3,000 · sample'],['Publishing','Approval required']], stages:['Stay window','Creative & budget','Review','Approved action'] },
  { key:'social', icon:Image, name:'Social content', title:'The villa, the artwork and the caption — together.', text:'Prepare social artwork, captions and community-post drafts around real availability. Your team can download the content and handle manual posting; community-group publishing stays with people.', status:'Content draft · not posted', previewTitle:'An island escape, ready for a story.', previewBody:'Sample social artwork and caption for Villa Azure.', fields:[['Creative','Villa photo & caption'],['Review','Team checks the draft'],['Posting','Manual community posting']], stages:['Choose villa','Prepare artwork','Review caption','Download & post'] },
  { key:'newsletter', icon:Mail, name:'Newsletters', title:'A beautiful villa story, ready for your audience.', text:'Turn selected villas, photography and booking links into editable Mailchimp newsletters. AI helps draft the copy; your team previews the email, chooses the audience and approves sending.', status:'Newsletter preview · not sent', previewTitle:'Your next island escape.', previewBody:'A fictional newsletter preview with villa imagery and a booking-link placement.', fields:[['Provider','Mailchimp · configured account'],['Audience','Chosen by your team'],['Sending','Approval required']], stages:['Select villas','Draft & revise','Preview & audience','Approve sending'] },
];
export default function MarketingVisualStory() {
  const [selected,setSelected] = useState('campaigns');
  const mode = modes.find(item=>item.key===selected);
  const Icon = mode.icon;
  return <section className="marketing-visual-story" id="growth-in-action" aria-labelledby="growth-visual-title"><div className="marketing-story-shell"><div className="marketing-story-heading"><div><p>THE GROWTH WORKSPACE</p><h2 id="growth-visual-title">Great villas deserve<br /><em>to be seen.</em></h2></div><span>Connect available nights, creative work and reviewed campaigns to the business you already run.</span></div><div className="marketing-story-layout"><div className="marketing-story-scene"><img src={asset('/img/hostpilot-growth-workspace.webp')} alt="Illustrative desktop monitor showing a villa campaign planning and newsletter workspace" width="1672" height="941" loading="lazy" /><div className="marketing-story-scene-shade" /><div className="marketing-story-draft" aria-live="polite"><span><Icon size={15} />{mode.status}</span><img src={asset('/img/villa-sapphire-hero.jpg')} alt="Villa image used in the fictional marketing creative" width="1200" height="800" loading="lazy" /><h3>{mode.previewTitle}</h3><p>{mode.previewBody}</p><small>ILLUSTRATIVE PREVIEW · NO LIVE CAMPAIGN</small></div><span className="marketing-story-scene-label">THE MARKETING LAYER AROUND YOUR VILLA OPERATION.</span></div><div className="marketing-story-workflow"><div className="marketing-story-switch" role="group" aria-label="Explore growth workflows">{modes.map(item=>{const ItemIcon=item.icon;return <button key={item.key} type="button" aria-pressed={selected===item.key} onClick={()=>setSelected(item.key)}><ItemIcon size={16} />{item.name}</button>;})}</div><div className="marketing-story-description" aria-live="polite"><h3>{mode.title}</h3><p>{mode.text}</p><dl>{mode.fields.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><ol>{mode.stages.map((stage,index)=><li key={stage}><span>{index+1}</span>{stage}</li>)}</ol></div><div className="marketing-story-guard"><ShieldCheck size={18} /><p>Review stays in the workflow. Drafting content does not publish an ad, spend a budget or send a newsletter.</p></div><Link to="/capabilities#ops-features">See features & connection requirements <ArrowRight size={16} /></Link></div></div><p className="marketing-story-caption"><CalendarDays size={13} /> Scenes and sample budgets are illustrative. Credentials, provider permissions, audience selection and approval are required before live actions. Provider-reported conversions are not independently verified bookings.</p></div></section>;
}
