import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Building2, Layers } from 'lucide-react';
import './sales-pages.css';
export default function PortfolioQuote() {
  const [count,setCount]=useState(40);
  const [provider,setProvider]=useState('Hostaway');
  const size=count<20?'Under 20 villas':count<=50?'20–50 villas':count<=100?'50–100 villas':count<=200?'100–200 villas':'200+ villas';
  const query=new URLSearchParams({size,channel:provider,interest:'The full suite',villas:String(count)});
  return <section className="portfolio-quote shell" aria-labelledby="portfolio-quote-title"><div><p className="eyebrow">START WITH YOUR PORTFOLIO</p><h2 id="portfolio-quote-title">Your villas.<br /><span className="serif-em">Your rollout.</span></h2><p>Tell us the size of your operation and the booking system you use. We can shape the connection, onboarding and quote around your business.</p><div className="portfolio-quote-surfaces"><span>OPS</span><span>OWNER</span><span>GUEST</span><span>FIELD</span></div></div><div className="portfolio-quote-card"><div className="portfolio-quote-card-head"><Building2 size={21} /><span>YOUR PORTFOLIO</span><strong>{count} <small>villas</small></strong></div><label htmlFor="portfolio-villa-count">Number of villas</label><input id="portfolio-villa-count" type="range" min="1" max="250" step="1" value={count} onChange={event=>setCount(Number(event.target.value))} /><div className="portfolio-quote-range-labels"><span>1 villa</span><span>250 villas</span></div><label htmlFor="portfolio-booking-provider">Your booking system</label><select id="portfolio-booking-provider" value={provider} onChange={event=>setProvider(event.target.value)}>{['Hostaway','Guesty','Lodgify','Other / not selected'].map(name=><option key={name}>{name}</option>)}</select><div className="portfolio-quote-connection"><Layers size={16} /><p>{provider==='Hostaway'?'Hostaway is supported in the current operation. Your account is configured and validated during rollout.':provider==='Other / not selected'?'Tell us about your current setup. We will agree the connection scope before onboarding.':'This adapter is planned. API access and supported workflows need testing before availability.'}</p></div><Link to={`/demo?${query}`} className="btn btn-gold">Discuss this portfolio <ArrowRight size={16} /></Link><small className="portfolio-quote-note">A quote enquiry, not a subscription checkout. Final rates are discussed with your team.</small></div></section>;
}
