import { Link } from 'react-router-dom';
import { ArrowRight, Play, CheckCircle2, Camera, Wallet, ScanLine } from 'lucide-react';
import asset from '../lib/asset.js';
import './product-visual-hero.css';

export default function ProductVisualHero({ visual, eyebrow, title, lede, tourTo, bullets }) {
  const Icon = visual.kind === 'owner' ? Wallet : visual.kind === 'ops' ? ScanLine : CheckCircle2;
  return <section className="product-visual-hero" aria-labelledby="product-visual-heading"><div className="product-hero-shell"><div className="product-hero-copy"><p className="product-hero-eyebrow">{eyebrow} / THE CONNECTED VILLA BUSINESS</p><h1 id="product-visual-heading">{title}</h1><p>{lede}</p><div className="product-hero-actions"><Link to={tourTo} className="product-hero-primary"><Play size={14} fill="currentColor" />{visual.kind === 'ops' ? 'See the real Ops screens' : 'Explore the interactive tour'}<ArrowRight size={16} /></Link><Link to="/demo" className="product-hero-secondary">Talk about your portfolio <ArrowRight size={16} /></Link></div><div className="product-hero-proof"><CheckCircle2 size={15} /> Built at Mr Property Siam · demonstrated with sample data</div>{bullets.length > 0 && <details className="product-hero-included"><summary>See what’s included</summary><ul>{bullets.map(item => <li key={item}><CheckCircle2 size={13} />{item}</li>)}</ul></details>}</div><div className={`product-hero-art product-hero-art-${visual.kind}`}><img src={asset(visual.image)} alt={visual.alt} width={visual.width} height={visual.height} fetchPriority="high" /><div className="product-hero-art-shade" />{visual.kind === 'owner' && <div className="product-hero-camera-label"><Camera size={16} /><span>Smart-villa camera concept</span></div>}{visual.kind === 'ops' && <div className="product-hero-mini-screen"><div><span /><span /><span /><small>ACTUAL OPS INTERFACE</small></div><img src={asset('/img/real-ops/02-real-ops-finance-hub.jpg')} alt="Actual anonymised HostPilot Ops finance screen" width="1356" height="847" /></div>}<div className="product-hero-toast"><span><Icon size={19} /></span><div><small>ILLUSTRATIVE SOFTWARE EXPERIENCE</small><strong>{visual.notification}</strong><p>{visual.note}</p></div></div><div className="product-hero-art-caption">{visual.caption}</div></div></div><p className="product-hero-boundary">{visual.boundary}</p></section>;
}
