import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Bell, Camera, ScanLine, CheckCircle2, FileText, Wallet, ShieldCheck, Smartphone, ChevronRight } from 'lucide-react';
import asset from '../lib/asset.js';
import './visual-product-stories.css';

const alerts = [
  { key: 'payout', icon: Wallet, title: 'Your payout advice is ready.', short: 'Payout advice issued', time: 'Financial record', text: 'Owners receive payout advices by email and can find the record in their portal. Keep the supporting document close to the statement.', value: '฿142,800', label: 'Illustrative payout advice', link: '/owner' },
  { key: 'receipt', icon: CheckCircle2, title: 'A receipt, where it belongs.', short: 'Payment receipt available', time: 'Owner account', text: 'Receipts for payments recorded against an owner account stay in the portal, with an optional email copy. An uploaded bank slip still needs reconciliation.', value: '฿8,500', label: 'Illustrative recorded payment', link: '/owner' },
  { key: 'bill', icon: FileText, title: 'A bill with the whole story.', short: 'Supplier bill under review', time: 'Operations review', text: 'Capture the document, check the extracted details and assign the expense before submission. Keep the receipt evidence with the bill instead of losing it in a chat.', value: '฿2,450', label: 'Illustrative supplier bill', link: '/ops' },
];
const scanSteps = [
  { name: 'Capture', title: 'A photo becomes a starting point.', text: 'Photograph or upload a supplier bill. The scanner reads the document and prepares extracted details for review.', status: 'Document captured', fields: [['Source', 'Receipt photo'], ['Property', 'Choose a villa'], ['Next step', 'Check extracted details']] },
  { name: 'Review', title: 'Your team stays in control.', text: 'Check the supplier, amount, category and villa. Correct the extracted information before it enters the approval workflow.', status: 'Ready for review', fields: [['Supplier', 'Island Pool Supplies'], ['Amount', '฿2,450.00'], ['Property', 'Villa Azure']] },
  { name: 'Submit', title: 'Evidence follows the expense.', text: 'Submit the reviewed bill for the relevant approval. The document stays attached; a scan does not automatically approve an expense or prove payment.', status: 'Awaiting review', fields: [['Category', 'Pool maintenance'], ['Evidence', 'Receipt attached'], ['Status', 'Awaiting review']] },
];

function NotificationDemo() {
  const [active, setActive] = useState('payout');
  const alert = alerts.find(item => item.key === active);
  const Icon = alert.icon;
  return <section className="product-notifications cinema-shell" aria-labelledby="notifications-title">
    <div className="product-notification-copy"><p className="cinema-eyebrow">THE DETAILS THAT BUILD TRUST</p><h2 id="notifications-title">The right update.<br /><em>Without the chasing.</em></h2><p>A payout advice. A payment receipt. A supplier bill ready for review. Turn everyday financial events into clear, accessible records.</p><div className="product-alert-picker" role="group" aria-label="Explore example financial updates">{alerts.map(item => { const ItemIcon = item.icon; return <button key={item.key} type="button" aria-pressed={active === item.key} onClick={() => setActive(item.key)}><ItemIcon size={19} /><span>{item.short}</span><ChevronRight size={16} /></button>; })}</div><p className="product-visual-caption">Illustrative examples. Email availability follows configured workflows and notification preferences.</p></div>
    <div className="product-notification-stage"><div className="product-phone"><div className="product-phone-speaker" /><div className="product-phone-header"><span>HostPilot <b>OWNER</b></span><Bell size={18} /></div><span className="product-device-eyebrow">YOUR VILLA. YOUR RECORDS.</span><h3>Everything<br />in its place.</h3><div className="product-phone-villa"><img src={asset('/img/villa-day.jpg')} alt="Illustrative owner property, Villa Azure" loading="lazy" /><span>VILLA AZURE</span></div><div className="product-phone-update" aria-live="polite"><span><Icon size={16} />{alert.time}</span><h4>{alert.title}</h4><strong>{alert.value}</strong><p>{alert.label}</p><Link to={alert.link}>Explore the portal <ArrowRight size={14} /></Link></div><div className="product-phone-bottom"><span>Overview</span><span>Documents</span><span>Updates</span></div></div><div className="product-floating-alert" aria-live="polite"><span className="product-alert-icon"><Icon size={19} /></span><div><small>HOSTPILOT PRO · DEMO UPDATE</small><strong>{alert.short}</strong><span>Villa Azure · supporting record available</span></div><CheckCircle2 size={16} /></div><div className="product-notification-description" aria-live="polite"><p>{alert.text}</p></div></div>
  </section>;
}

function ScannerStory() {
  const [step, setStep] = useState(1);
  const scan = scanSteps[step];
  return <section className="product-scanner"><div className="cinema-shell product-two-column"><div className="product-scanner-image"><img src={asset('/img/hostpilot-bill-scanner.webp')} alt="Illustrative staff member using a smartphone to photograph a supplier receipt" loading="lazy" width="1086" height="1448" /><div className="product-scan-result" aria-live="polite"><div><ScanLine size={17} /><span>HOSTPILOT BILL SCANNER</span></div><h4>{scan.status}</h4>{scan.fields.map(([label,value]) => <p key={label}><span>{label}</span><strong>{value}</strong></p>)}<small>Illustrative workflow · sample data</small></div><span className="product-image-label">SOFTWARE THAT MEETS YOUR TEAM WHERE THEY WORK.</span></div><div className="product-scanner-copy"><p className="cinema-eyebrow">FROM PAPER TO A PROPER RECORD</p><h2>Point. Capture.<br /><em>Keep the evidence.</em></h2><p>Less typing. Fewer missing receipts. A bill scanner built into the operation, with a review step that keeps the team accountable.</p><div className="product-scan-steps" role="group" aria-label="Explore the bill-scanning workflow">{scanSteps.map((item,index) => <button key={item.name} type="button" aria-pressed={step === index} onClick={() => setStep(index)}><span>0{index+1}</span>{item.name}</button>)}</div><div className="product-scan-description" aria-live="polite"><h3>{scan.title}</h3><p>{scan.text}</p></div><Link to="/capabilities" className="cinema-text-link">Explore finance & operations <ArrowRight size={17} /></Link></div></div></section>;
}

export default function VisualProductStories() {
  return <div className="product-visual-stories">
    <section className="product-owner-story cinema-shell" id="software-in-action" aria-labelledby="owner-visual-title"><div className="cinema-section-intro"><div><p className="cinema-eyebrow">YOUR PROPERTY. A CLOSER CONNECTION.</p><h2 id="owner-visual-title">A window into the villa.<br /><em>From wherever you are.</em></h2></div><p>Show owners the property, the financial records and the decisions around it — through an experience designed for them.</p></div><div className="product-owner-scene"><img src={asset('/img/hostpilot-owner-laptop.webp')} alt="Illustrative villa owner checking a laptop displaying a proposed owner dashboard with exterior camera views" width="1672" height="941" loading="lazy" /><div className="product-owner-scene-shade" /><div className="product-camera-tag"><Camera size={17} /><div><strong>Smart-villa view</strong><span>Camera connection concept</span></div><span className="product-concept-dot" /></div><div className="product-owner-toast"><Wallet size={19} /><div><small>ILLUSTRATIVE FINANCIAL UPDATE</small><strong>Your payout advice is ready.</strong><span>Open the supporting record in your portal.</span></div></div><div className="product-owner-scene-caption"><span>THE OWNER EXPERIENCE</span><h3>Closer to the property.<br />Clearer on the numbers.</h3><Link to="/owner">Explore HostPilot Owner <ArrowRight size={17} /></Link></div></div><div className="product-owner-feature-line"><span><Wallet size={17} />Statements & payout records</span><span><Bell size={17} />Financial updates</span><span><ShieldCheck size={17} />Supporting documents</span><span><Camera size={17} />Smart-villa concept</span></div><p className="product-visual-caption">Lifestyle scenes and device screens are illustrative. Exterior camera viewing is a proposed integration, not a verified live feed; availability depends on device support and authorised property access.</p></section>
    <NotificationDemo />
    <ScannerStory />
    <section className="product-guest-story cinema-shell"><div className="product-guest-copy"><p className="cinema-eyebrow">HOSPITALITY, IN THEIR HANDS</p><h2>The villa experience.<br /><em>In their pocket.</em></h2><p>Arrival instructions, house essentials and the little extras that make a stay memorable. Give guests a useful app experience, instead of another document to find.</p><div className="product-guest-points"><span><Smartphone size={18} />Arrival & villa guide</span><span><CheckCircle2 size={18} />Service requests & extras</span><span><Wallet size={18} />Configured payment options</span></div><Link to="/guest" className="cinema-text-link">Explore HostPilot Guest <ArrowRight size={17} /></Link></div><div className="product-guest-image"><img src={asset('/img/hostpilot-guest-phone.webp')} alt="Illustrative guest holding a smartphone with a villa stay app beside a tropical infinity pool" loading="lazy" width="1448" height="1086" /><div className="product-guest-toast"><CheckCircle2 size={19} /><div><small>ILLUSTRATIVE SERVICE REQUEST</small><strong>Airport transfer requested</strong><span>Your villa team can review the request.</span></div></div><span className="product-image-label">AN EXCEPTIONAL STAY STARTS WITH THE DETAILS.</span></div></section>
  </div>;
}
